# Generated by Django 5.0.3 on 2024-03-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tst", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="team_a",
        ),
        migrations.RemoveField(
            model_name="match",
            name="team_b",
        ),
        migrations.AddField(
            model_name="match",
            name="team_a",
            field=models.ManyToManyField(related_name="team_a", to="tst.player"),
        ),
        migrations.DeleteModel(
            name="Team",
        ),
        migrations.AddField(
            model_name="match",
            name="team_b",
            field=models.ManyToManyField(related_name="team_b", to="tst.player"),
        ),
    ]
